# Generated by Django 4.1.3 on 2022-11-29 08:18

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chat',
            name='date_added',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
    ]
