# Generated by Django 4.1.3 on 2022-11-29 08:22

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0002_alter_chat_date_added'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chat',
            name='date_added',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
