# Generated by Django 4.1.3 on 2022-11-29 09:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_remove_user_is_verified'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='username_edit',
            field=models.BooleanField(default=False),
        ),
    ]
